<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net48;net8.0;net10.0</TargetFrameworks>
    <Configurations>Debug;Release</Configurations>
    <DebugType>embedded</DebugType>
    <NoWarn>NETSDK1138;CS1587</NoWarn>
    <EnablePackageValidation>true</EnablePackageValidation>
    <Title>$(AssemblyName)</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>SafeTwice S.L.</Authors>
    <PackageProjectUrl>https://github.com/SafeTwice/Utilities.DotNet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SafeTwice/Utilities.DotNet.git</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>.net;dotnet;utilities;util;collection;collections</PackageTags>
    <Company>www.safetwice.com</Company>
    <Description>Collection utilities library for .NET</Description>
    <Copyright>Copyright © 2025 SafeTwice S.L.</Copyright>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <Version>1.5-rc.2</Version>
    <AssemblyVersion>1.5.0.2</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_EVENT_NAME)' == 'release'">
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="2.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
