<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(Configuration.EndsWith(`NoI18N`))' == 'true'">
    <AssemblyName>$(AssemblyName)-NoI18N</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net472;net48;net6.0;net7.0;net8.0</TargetFrameworks>
    <Configurations>Debug;Release;Profile;Debug-NoI18N;Release-NoI18N;Profile-NoI18N</Configurations>
    <DebugType>embedded</DebugType>
    <NoWarn>NETSDK1138;CS1587</NoWarn>
    <EnablePackageValidation>true</EnablePackageValidation>
    <Title>$(AssemblyName)</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>SafeTwice S.L.</Authors>
    <PackageProjectUrl>https://github.com/SafeTwice/Utilities.DotNet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SafeTwice/Utilities.DotNet.git</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>.net;dotnet;utilities</PackageTags>
    <Company>www.safetwice.com</Company>
    <Description>Utilities library for .NET</Description>
    <Copyright>Copyright © 2025 SafeTwice S.L.</Copyright>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Nullable>enable</Nullable>
    <LangVersion>11</LangVersion>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <Version>1.5-rc5</Version>
    <AssemblyVersion>1.5.0.5</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_EVENT_NAME)' == 'release'">
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration.StartsWith(`Profile`))' == 'true'">
    <DefineConstants>$(DefineConstants);PROFILE</DefineConstants>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration.Contains(`NoI18N`))' == 'false'">
    <DefineConstants>$(DefineConstants);USE_I18N_LIB</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration.Contains(`NoI18N`))' == 'false'">
    <EmbeddedResource Include="Resources\I18N.xml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Exceptions\Utilities.DotNet.Exceptions.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration.Contains(`Debug`))' == 'false'">
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <OutDir>bin/$(TargetFramework)/$(Configuration)</OutDir>
    <PackageOutputPath Condition="'$(PackageOutputPath)' == ''">bin\</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration.Contains(`Debug`))' == 'false'">
    <Content Include="bin/*/Release/Utilities.DotNet.dll" Pack="true" PackagePath="lib" Visible="false" />
    <Content Include="bin/*/Profile/Utilities.DotNet.dll" Pack="true" PackagePath="lib" Visible="false" />
    <Content Include="bin/*/Release/Utilities.DotNet.xml" Pack="true" PackagePath="lib" Visible="false" />
    <Content Include="bin/*/Profile/Utilities.DotNet.xml" Pack="true" PackagePath="lib" Visible="false" />
    <Content Include="buildTransitive/**/*" Pack="true" PackagePath="buildTransitive" />
  </ItemGroup>

</Project>
